import type { GitHubUser, GitHubRepository } from '@/types/github'

export const mockUser: GitHubUser = {
  id: 1,
  login: 'torvalds',
  name: 'Linus Torvalds',
  avatar_url: 'https://avatars.githubusercontent.com/u/1',
  html_url: 'https://github.com/torvalds',
  bio: 'Creator of Linux and Git',
  email: null,
  location: 'Portland, OR',
  company: 'Linux Foundation',
  blog: 'https://linuxfoundation.org',
  twitter_username: null,
  public_repos: 5,
  public_gists: 0,
  followers: 232000,
  following: 0,
  created_at: '2011-09-03T15:26:22Z',
  updated_at: '2024-01-01T00:00:00Z',
}

export const mockRepository: GitHubRepository = {
  id: 101,
  name: 'linux',
  full_name: 'torvalds/linux',
  description: 'Linux kernel source tree',
  html_url: 'https://github.com/torvalds/linux',
  clone_url: 'https://github.com/torvalds/linux.git',
  ssh_url: 'git@github.com:torvalds/linux.git',
  homepage: null,
  language: 'C',
  stargazers_count: 180000,
  watchers_count: 180000,
  forks_count: 55000,
  open_issues_count: 300,
  size: 4500000,
  default_branch: 'master',
  topics: ['linux', 'kernel', 'operating-system'],
  private: false,
  fork: false,
  archived: false,
  created_at: '2011-09-04T22:48:12Z',
  updated_at: '2024-11-01T10:00:00Z',
  pushed_at: '2024-11-01T09:55:00Z',
  owner: {
    login: 'torvalds',
    avatar_url: 'https://avatars.githubusercontent.com/u/1',
    html_url: 'https://github.com/torvalds',
  },
  license: {
    name: 'GNU General Public License v2.0',
    spdx_id: 'GPL-2.0',
  },
  visibility: 'public',
}

export const mockRepositories: GitHubRepository[] = [
  mockRepository,
  {
    ...mockRepository,
    id: 102,
    name: 'git',
    full_name: 'torvalds/git',
    description: 'Git source code',
    language: 'C',
    stargazers_count: 50000,
    forks_count: 25000,
    topics: ['git', 'version-control'],
    updated_at: '2024-10-01T10:00:00Z',
  },
  {
    ...mockRepository,
    id: 103,
    name: 'aalib',
    full_name: 'torvalds/aalib',
    description: 'Portable ASCII art graphics library',
    language: 'C',
    stargazers_count: 1200,
    forks_count: 80,
    topics: [],
    updated_at: '2023-05-01T10:00:00Z',
  },
]
